services:
  postgres:
    container_name: 7x_postgres
    image: keti/sc/bigdatastorage/postgres:latest
    build:
      context: ./postgis
    restart: always
    hostname: 7x_postgres
    environment:
      TZ: Asia/Seoul
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: post123!
      NEW_DB_USER: hive
      NEW_DB_PASSWORD: hive123!
      NEW_DB_DATABASE: hive
    volumes:
      - ${POSTGRESQL_LOCAL_PATH}:/var/lib/postgresql/data
    ports:
      - 54321:5432

  hadoop:
    container_name: hadoop
    image: keti/sc/bigdatastorage/hadoop:latest
    build:
      context: ./hadoop
    restart: always
    hostname: hadoop
    environment:
      TZ: Asia/Seoul
      HADOOP_CONF_DIR: "/conf/hadoop"
    volumes:
      - ./conf:/conf
      - ${HADOOP_LOCAL_PATH}:/hdfs-data

  thrift:
    container_name: thrift
    image: keti/sc/bigdatastorage/thrift:latest
    build:
      context: ./thrift
    hostname: thrift
    environment:
      TZ: Asia/Seoul
      HADOOP_CONF_DIR: "/conf/hadoop"
    volumes:
      - ./conf/hadoop/core-site.xml:/usr/local/spark/conf/core-site.xml
      - ./conf/hadoop/yarn-site.xml:/usr/local/spark/conf/yarn-site.xml
      - ./conf/hadoop/hdfs-site.xml:/usr/local/spark/conf/hdfs-site.xml
      - ./conf/hive/hive-site.xml:/usr/local/spark/conf/hive-site.xml
    ports:
      - 10000:10000 # for thrift-server
      - 4040:4040

networks:
  default:
    name: citydatahub-datacore
    external: true
